# Generated by Django 5.2.4 on 2025-07-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='earnings',
            field=models.FloatField(default=0.0),
        ),
    ]
