# Generated by Django 5.2.3 on 2025-07-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_customuser_is_tutor_alter_customuser_username'),
        ('Authentication', '0002_roles_alter_customuser_password'),
    ]

    operations = [
    ]
