# Generated by Django 5.2.4 on 2025-07-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_customuser_is_tutor_alter_customuser_password_and_more'),
        ('Authentication', '0003_merge_20250708_0915'),
    ]

    operations = [
    ]
