# Generated by Django 5.2.4 on 2025-07-04 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SikhaiWhiteboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Untitled Sikahi Board', max_length=255)),
                ('elements', models.JSONField(default=list)),
                ('app_state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excalidraw_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sikhai Board',
                'verbose_name_plural': 'Sikhai Boards',
                'ordering': ['-updated_at'],
            },
        ),
    ]
