# Generated by Django 5.2.4 on 2025-07-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='google_meet_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
