# Generated by Django 5.2.4 on 2025-07-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_session_google_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
    ]
