# Generated by Django 5.2.4 on 2025-07-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_assignmentsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_files/'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
