# Generated by Django 5.2.4 on 2025-07-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('payments', '0001_initial'),
        ('tutor', '0004_assignment_assignment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='classroom',
            field=models.ManyToManyField(null=True, through='payments.OrderItem', to='tutor.classroom'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.classroom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='khalti_txn_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.ManyToManyField(null=True, through='payments.OrderItem', to='notes.note'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
    ]
