# Generated by Django 5.2.4 on 2025-07-29 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('payments', '0002_order_classroom_orderitem_classroom_and_more'),
        ('tutor', '0004_assignment_assignment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='classroom',
        ),
        migrations.CreateModel(
            name='OrderClassroomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.classroom')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_items', to='payments.order')),
            ],
            options={
                'unique_together': {('order', 'classroom')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='classrooms',
            field=models.ManyToManyField(related_name='orders', through='payments.OrderClassroomItem', to='tutor.classroom'),
        ),
        migrations.CreateModel(
            name='OrderNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_items', to='payments.order')),
            ],
            options={
                'unique_together': {('order', 'note')},
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.ManyToManyField(related_name='orders', through='payments.OrderNoteItem', to='notes.note'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
