# Generated by Django 5.2.4 on 2025-07-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_completed_todo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='todo',
        ),
    ]
