# Generated by Django 5.2.4 on 2025-07-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
